version: '3.7'

networks:
  map_mc:
    driver: bridge

services:
  db:
    image: postgres
    container_name: db_map
    ports:
      - "2323:5432"
    networks:
      - map_mc
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    container_name: mc-map
    ports:
      - "8002:8000"
    env_file:
      - .env-non-dev
    depends_on:
      - db